// <auto-generated />
using DevHire.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevHire.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220813150619_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DevHire.Data.Dev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Fee")
                        .HasColumnType("float");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fee = 1000.0,
                            IsFavourite = true,
                            IsHired = false,
                            Name = "Bernard Promise",
                            Skill = "Frontend Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Fee = 5000.0,
                            IsFavourite = false,
                            IsHired = true,
                            Name = "Sunday Ogbonna",
                            Skill = "Frontend Engineer with react"
                        },
                        new
                        {
                            Id = 3,
                            Fee = 7000.0,
                            IsFavourite = true,
                            IsHired = false,
                            Name = "Favour Ebrusike",
                            Skill = "Fullstack Engineer"
                        },
                        new
                        {
                            Id = 4,
                            Fee = 10000.0,
                            IsFavourite = true,
                            IsHired = true,
                            Name = "Zikorah",
                            Skill = "Project Manager"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
